version: "3.8"

networks:
  network_public:
    external: true

services:
  vaultwarden:
    image: vaultwarden/server:1.28.1-alpine
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.docker.network=network_public
        - traefik.http.routers.vaultwarden.tls=true
        - traefik.http.routers.vaultwarden.rule=Host(`${DOMAIN}`) && PathPrefix(`/vaultwarden`)
        - traefik.http.routers.vaultwarden.service=vaultwarden
        - traefik.http.services.vaultwarden.loadbalancer.server.port=80
        - traefik.http.routers.vaultwarden-websocket.tls=true
        - traefik.http.routers.vaultwarden-websocket.rule=Host(`${DOMAIN}`) && Path(`/notifications/hub`)
        - traefik.http.routers.vaultwarden-websocket.service=vaultwarden-websocket
        - traefik.http.services.vaultwarden-websocket.loadbalancer.server.port=3012
    hostname: vaultwarden
    env_file:
      - .env_vaultwarden
    volumes:
      - /media/disk2/volumes/vaultwarden:/data:rw
    networks:
      - network_public
