version: "3.8"

networks:
  traefik_public:
    external: true

volumes:
  pihole:

secrets:
  pihole_admin_password:
    file: ./secrets/pihole_admin_password.txt

services:
  pihole:
    image: pihole/pihole:2023.03.1
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.pihole.rule=PathPrefix(`/admin`)"
        - "traefik.http.routers.pihole.tls=true"
        - "traefik.http.services.pihole.loadbalancer.server.port=80"
    hostname: pihole
    env_file:
      - .env_pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - pihole:/etc
      - ./pihole/custom.list:/etc/pihole/custom.list:ro
      - /etc/resolv.conf:/etc/resolv.conf:ro
    secrets:
      - pihole_admin_password
    networks:
      - traefik_public

